### ISSUE TITLE
TypeError: context.iconsCache is not a function

### ISSUE THREAD

**Issue by JohanCDev** [mengxinssfd/typedoc-theme#6]
Hey @mengxinssfd !

When I try to run typedoc with a theme I get an error

```
TypeDoc exiting with unexpected error:
TypeError: context.iconsCache is not a function
    at defaultLayout (/Users/johan/NoLoSay/NoLoApp/node_modules/@mxssfd/typedoc-theme/dist/templates/defaultLayout.js:51:21)
    at ThemeContext.defaultLayout (/Users/johan/NoLoSay/NoLoApp/node_modules/@mxssfd/typedoc-theme/dist/ThemeContext.js:7:22)
    at DefaultTheme.defaultLayoutTemplate (/Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/output/themes/default/DefaultTheme.js:37:53)
    at MyTheme.render (/Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/output/themes/default/DefaultTheme.js:168:37)
    at Renderer.renderDocument (/Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/output/renderer.js:184:40)
    at /Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/output/renderer.js:160:22
    at Array.forEach (<anonymous>)
    at Renderer.render (/Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/output/renderer.js:158:25)
    at async Application.generateDocs (/Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/application.js:309:9)
    at async run (/Users/johan/NoLoSay/NoLoApp/node_modules/typedoc/dist/lib/cli.js:110:13)
```

The command I use is `typedoc --options ./typedoc.json`

typedoc.json being
```{
  "entryPoints": ["./src/**/*.tsx"],
  "out": "docs/documentation",
  "tsconfig": "tsconfig.json",
  "plugin": ["@mxssfd/typedoc-theme"],
  "theme": "my-theme",
  "name": "NoLoApp",
  "customCss": "docs/setup/assets/style.css",
  "includeVersion": true
}```

Do you have any Idea of why this happens ? Thanks a lot !

**Comment by mengxinssfd** [comment]
Apologies for the delay. 
I've reviewed the dependencies in your project and identified that the error is caused by the outdated version of Typedoc (0.24.8). Simply updating Typedoc to the latest version should resolve the issue.

**Comment by JohanCDev** [comment]
Oups, thank you 😅❤️

**Comment by mengxinssfd** [comment]
😄❤️
